#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=99
IPC="/usr/sbin/ip"
IFCONFIG="/sbin/ifconfig"
CANIF="can0"

# enable gpio as output to control reset pin on mikroe bus ch#1
echo 5 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio5/direction
echo 1 > /sys/class/gpio/gpio5/value

# configure and enable can0 interface
$IPC link set $CANIF type can bitrate 125000 triple-sampling on
$IFCONFIG $CANIF up
