#!/bin/sh

[ "$(uci get system.@system[-1].arancino_firstboot)" = "1" ] && return 0
. /lib/functions.sh

config_load network

set_network_interface() {
	uci set network.lan=interface
	uci delete network.lan.type
	uci set network.lan.ifname='wlan0'
	uci set network.lan.proto='static'
	uci set network.lan.ipaddr='192.168.240.1'
	uci set network.lan.dns='8.8.8.8, 8.8.4.4'

	uci set network.wan=interface
	uci set network.wan.ifname='eth0'
	uci set network.wan.proto='dhcp'
	uci set network.wan.metric='10'
	uci set network.wan.dns='8.8.8.8, 8.8.4.4'
	uci commit network

	uci set network.wwan=interface
	uci set network.wwan.ifname='eth1'
	uci set network.wwan.proto='dhcp'
	uci set network.wwan.metric='20'
	uci set network.wwan.dns='8.8.8.8, 8.8.4.4'
	uci commit network
}

disable_ipv6_sysctl_conf() {
	echo "net.ipv6.conf.all.disable_ipv6=1" >> /etc/sysctl.conf
	echo "net.ipv6.conf.default.disable_ipv6=1" >> /etc/sysctl.conf
}

set_network_interface
disable_ipv6_sysctl_conf
exit 0
