#!/bin/sh

# LDR_VER=`grep UBOOTVER= /dev/mtd0 | cut -d= -f2`
# [ -z "${LDR_VER}" ] && LDR_VER=0.8.2

uci set system.@system[0].firmware_version=v0.0.1
# uci set system.@system[0].loader_version=v${LDR_VER}
uci set system.@system[0].arancino_firstboot=1

uci set system.@system[0].log_file=/var/log/messages
uci set system.@system[0].log_size=1024
uci set system.@system[0].log_type=file

uci commit system
