#!/bin/sh

[ "$(uci get system.@system[-1].arancino_firstboot)" = "1" ] && return 0
. /lib/functions.sh

config_load system

set_hostname() {
	uci set system.@system[0].hostname='picoGW'
	uci commit system
	exit 0
}

set_hostname
exit 0
