#!/bin/sh

[ "$(uci get system.@system[-1].arancino_firstboot)" = "1" ] && return 0
. /lib/functions.sh

config_load dhcp

set_dhcp_interface() {
	uci set dhcp.interface='lo,wwan'
	uci set dhcp.@dnsmasq[0].rebind_protection='0'
	uci commit dhcp
	exit 0
}

set_dhcp_interface
exit 0
