#!/bin/sh

FTDI_PRODID="403/6001/600"
SYMLINK="ttyFTDI"
BAUDRATE=115200


#env >> /tmp/hotplug.log

if [ "${PRODUCT}" = "${FTDI_PRODID}" ];
   then if [ "${ACTION}" = "add" ];
      then
         DEVICE_NAME=$(ls /sys/$DEVPATH/$DEVICENAME":1.0" | grep tty)
         if [ -z ${DEVICE_NAME} ];
            then logger -t Hotplug Warning DEVICE_NAME is empty
            exit
         fi
         logger -t Hotplug Device name of ftdi is $DEVICE_NAME
         ln -s /dev/$DEVICE_NAME /dev/${SYMLINK}
         stty -F /dev/${SYMLINK} ${BAUDRATE}
         logger -t Hotplug Symlink from /dev/$DEVICE_NAME to /dev/${SYMLINK} created
   fi
fi

if [ "${PRODUCT}" = "${FTDI_PRODID}" ];
   then if [ "${ACTION}" = "remove" ];
         then
         rm /dev/${SYMLINK}
         logger -t Hotplug Symlink /dev/${SYMLINK} removed
   fi
fi

