#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=99
IPC="/sbin/ip"
IFCONFIG="/sbin/ifconfig"
CANIF="can0"

start() {
	# configure and enable can0 interface
	$IPC link set $CANIF type can bitrate 250000 triple-sampling on
	$IFCONFIG $CANIF up
}

stop() {
	$IFCONFIG $CANIF down
}
