#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=11
STOP=11

baudcmd="\xaa"

start() {
	source /etc/config/mcuiocfg
	# Reset mcu
	#mcu-reset
	#sleep 2
	# Init serial port at 250kbps (default for bathos-mcuio.hex at boot)
	stty 230400 -echo raw < /dev/ttyS0

	#set default value for baudrate
	if [ -z $BAUDRATE ]; then 
		BAUDRATE=230400 
	fi

	if [ $BAUDRATE -eq 230400 ]; then
		baudcmd="\xaa"
	elif [ $BAUDRATE -eq 460800 ]; then
		baudcmd="\xab"
	fi
	# Make MCU to switch to mcuio mode
	echo -n -e $baudcmd > /dev/ttyS0
	# Set serial port baudrate
	stty $BAUDRATE -echo raw < /dev/ttyS0
	# Start ldattach to set line discipline N_MCUIO=29
	ldattach 29 /dev/ttyS0
}

stop() {
	killall ldattach
	#mcu-reset
}
